version: '2'
services:
  web:
    build: .
    command: npm run dev
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3001:3001"
    links:
      - postgres

  postgres:
    image: postgres:9.6.3-alpine
    environment:
      POSTGRES_USER: bookly_dev_user
      POSTGRES_DB: bookly_dev
