version: '2'
services:
  node:
    build:
      context: .
      dockerfile: ./scripts/docker/node/Dockerfile
    ports:
      - "3001"
    links:
      - postgres

  postgres:
    image: postgres:9.6.3-alpine
    environment:
      POSTGRES_USER: bookly_dev_user
      POSTGRES_DB: bookly_dev
