version: '3'
services:
  web:
    build: ./scripts/docker/nginx/
    links:
      - node
    ports:
      - "80:80"

  node:
    build:
      context: .
      dockerfile: ./scripts/docker/node/Dockerfile
    command: npm run dev
    ports:
      - "3001"
